const postDetails = [
  {
    id: "1",
    title: "New app for gaming",
    subTitle: "Install and enjoy the fast",
    image: require("../assets/images/pic.jpg"),
    percetage: "37",
    pledged: "$8767",
    days: "5",
    likes: "4561",
    tag: "Technology",
    location: "Manglore,Karnataka,India",
  },
  {
    id: "2",
    title: "New app for gaming",
    subTitle: "Install and enjoy the fast",
    image: require("../assets/images/pic.jpg"),
    percetage: "78",
    pledged: "$8767",
    days: "5",
    likes: "4561",
    tag: "Food",
    location: "Kannur,Kerala",
  },
  {
    id: "3",
    title: "New app for gaming",
    subTitle: "Install and enjoy the fast",
    image: require("../assets/images/pic.jpg"),
    percetage: "67",
    pledged: "$8767",
    days: "5",
    likes: "4561",
    tag: "App",
    location: "Taliparamba,Kerala",
  },
  {
    id: "4",
    title: "New app for gaming",
    subTitle: "Install and enjoy the fast",
    image: require("../assets/images/pic.jpg"),
    percetage: "67",
    pledged: "$8767",
    days: "5",
    likes: "4561",
    tag: "App",
    location: "Taliparamba,Kerala",
  },
];

export default {
  postDetails,
};
