export default Object.freeze({
  LOGIN: "Login",
  REGISTER_1: "Register",
  REGISTER_2: "OTP",
  REGISTER_3: "Password",
  POST_LIST: "PostList",
  POST_DETAILS: "PostDetails",
  PROFILE: "Profile",
  NOTIFICATION: "Notification",
  SEARCH: "Search",
  COMMENT: "Comment",
  CHARITY: "Charity",
  KICKSTARTER: "KickStarter",
  AFTERAPPLIED: "AfterApplied",
  NEW_POST: "AddPost",
});
